# Generated by Django 5.2.9 on 2026-02-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ORS", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicleName", models.CharField(max_length=50)),
                ("vehicleNumber", models.CharField(max_length=50)),
                ("licenseDate", models.DateField()),
                ("vehicleOwner", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "sos_vehicle",
            },
        ),
    ]
