# Generated by Django 5.2.9 on 2026-02-04 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ORS", "0002_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("attendanceId", models.IntegerField()),
                ("personName", models.CharField(max_length=50)),
                ("attendanceDate", models.DateField()),
                ("attendanceStatus", models.CharField(max_length=50)),
                ("remarks", models.CharField(max_length=500)),
            ],
            options={
                "db_table": "sos_attendance",
            },
        ),
    ]
