# Generated by Django 5.2.9 on 2026-02-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ORS", "0003_attendance"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inquiryId", models.IntegerField()),
                ("inquiryName", models.CharField(max_length=50)),
                ("inquiryDate", models.DateField()),
                ("email", models.EmailField(max_length=254)),
                ("inquirySubject", models.CharField(max_length=50)),
                ("inquiryStatus", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "sos_inquiry",
            },
        ),
    ]
