from Tools.scripts.fixdiv import report

from .BaseCtl import BaseCtl
from django.shortcuts import render

from ..models import Reports
from ..utility.DataValidator import DataValidator
from ..service.ReportService import ReportService


class ReportCtl(BaseCtl):

    def request_to_form(self, requestForm):
        self.form['id'] = requestForm.get('id', 0)
        self.form['reportId'] = requestForm.get('reportId')
        self.form['reportName'] = requestForm.get('reportName')
        self.form['generatedDate'] = requestForm.get('generatedDate')
        self.form['generatedBy'] = requestForm.get('generatedBy')
        self.form['reportStatus'] = requestForm.get('reportStatus')

    def form_to_model(self, obj):
        pk = int(self.form['id'])
        if pk > 0:
            obj.id = pk
        obj.reportId = self.form['reportId']
        obj.reportName = self.form['reportName']
        obj.generatedDate = self.form['generatedDate']
        obj.generatedBy = self.form['generatedBy']
        obj.reportStatus = self.form['reportStatus']
        return obj

    def model_to_form(self, obj):
        if (obj == None):
            return
        self.form['reportId'] = obj.reportId
        self.form['reportName'] = obj.reportName
        self.form['generatedDate'] = obj.generatedDate
        self.form['generatedBy'] = obj.generatedBy
        self.form['reportStatus'] = obj.reportStatus


    def input_validation(self):
        super().input_validation()
        inputError = self.form["inputError"]

        if DataValidator.isNull(self.form['reportId']):
            inputError['reportId'] = "Report Id can not be null"
            self.form['error'] = True
        elif not DataValidator.ischeckroll(self.form['reportId']):
            inputError['reportId'] = "Report Id must be alphanumeric"
            self.form['error'] = True

        if DataValidator.isNull(self.form["reportName"]):
            inputError["reportName"] = "Report Name is required"
            self.form["error"] = True

        if (DataValidator.isNull(self.form["generatedDate"])):
            inputError["generatedDate"] = "generatedDate is required"
            self.form["error"] = True
        else:
            if (DataValidator.isDate(self.form['generatedDate'])):
                inputError['generatedDate'] = "Incorrect Date of birth"
                self.form['error'] = True

        if DataValidator.isNull(self.form["generatedBy"]):
            inputError["generatedBy"] = "Generated By is required"
            self.form["error"] = True

        if DataValidator.isNull(self.form["reportStatus"]):
            inputError["reportStatus"] = "Report Status is required"
            self.form["error"] = True

        return self.form['error']

    def display(self, request, params={}):
        if (params['id'] > 0):
            report = self.get_service().get(params['id'])
            self.model_to_form(report)
        res = render(request, self.get_template(), {"form": self.form})
        return res

    def submit(self, request, params={}):
        if (int(self.form['id']) > 0):
            pk = int(self.form['id'])
            duplicate = self.get_service().get_model().objects.exclude(id=pk).filter(reportName=self.form['reportName'])
            if duplicate.count() > 0:
                self.form['error'] = True
                self.form['message'] = "Report already exist"
                res = render(request, self.get_template(), {'form': self.form})
            else:
                report= self.form_to_model(Reports())
                self.get_service().save(report)
                self.form['id'] = report.id
                self.form['error'] = False
                self.form['message'] = "Report updated successfully"
                res = render(request, self.get_template(), {'form': self.form})
        else:
            duplicate = self.get_service().get_model().objects.filter(reportId=self.form['reportId'])

            if duplicate.count() > 0:
                self.form['error'] = True
                self.form['message'] = "Report already exist"
                res = render(request, self.get_template(), {'form': self.form})
            else:
                report = self.form_to_model(Reports())
                self.get_service().save(report)
                self.form['error'] = False
                self.form['message'] = "Report added successfully..!!"
                res = render(request, self.get_template(), {'form': self.form})
        return res

    def get_template(self):
        return "Report.html"

    def get_service(self):
        return ReportService()